BEGIN;

DROP TABLE IF EXISTS "coffee";

CREATE TABLE IF NOT EXISTS "coffee" (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(128) NOT NULL,
  reference INT,
  origine VARCHAR(128),
  prix DECIMAL,
  caracteristique VARCHAR(128),
  description VARCHAR(128),
  disponible BOOLEAN
);

set client_encoding to utf8;

 INSERT INTO "coffee" ("nom","description","reference","origine","prix","caracteristique","disponible") VALUES 

 ( 'Espresso', 'Café fort et concentré préparé en faisant passer de l''eau chaude à travers du café finement moulu',  100955890, 'Italie', 20.99, 'Corsé', true),
 ('Columbian', 'Café moyennement corsé avec une acidité vive et une saveur riche', 100955894,'Colombie', 18.75, 'Acide', true),
 ('Ethiopian Yirgacheffe', 'Réputé pour son arôme floral, son acidité vive et ses notes de saveur citronnée', 105589090, 'Éthiopie', 22.50, 'Fruité', true),
 ('Brazilian Santos', 'Café doux et lisse avec un profil de saveur de noisette', 134009550,'Brésil', 17.80, 'Doux', true),
 ('Guatemalan Antigua', 'Café corsé avec des nuances chocolatées et une pointe d''épice', 256505890, 'Guatemala', 21.25, 'Corsé', true),
 ('Kenyan AA', 'Café complexe connu pour son acidité rappelant le vin et ses saveurs fruitées', 295432730, 'Kenya', 23.70,'Acide', true),
 ('Sumatra Mandheling', 'Café profond et terreux avec un corps lourd et une faible acidité', 302932754, 'Indonésie', 19.95, 'Corsé', true);

COMMIT;

